## Week 0, Part 1: Python Basics

In this tutorial we will cover some basic aspects of Python using IPython (Jupyter) notebooks. 

1. Syntax
2. Data types
3. Loops and control structures
4. numpy, scipy, math

### Import modules to use

In [1]:
import numpy as np
from scipy import stats
import math

### Syntax

In [2]:
2 + 2

4

In [3]:
x = 5
y = 2
x * y

10

In [4]:
x ** y

25

In [5]:
print('Hello, world!')

Hello, world!


In [6]:
print('%s raised to power of %s equals %s' % (x, y, x ** y))

5 raised to power of 2 equals 25


### Data types

#### Boolean

'True' and 'False' have special meaning in Python.

In [7]:
a = True
b = False

In [8]:
a == True

True

In [9]:
b == True

False

In [10]:
a or b

True

In [11]:
a and b

False

#### Numbers: integers and floats

Numbers are pretty straightforward, especially in Python 3.

In [12]:
1 + 2

3

In [13]:
1.0 + 2.0

3.0

In [14]:
1 / 2

0.5

In [15]:
1.0 / 2.0

0.5

In [16]:
type(1)

int

In [17]:
type(1/2)

float

#### Sequences: strings, lists, tuples

Strings are sequences of characters.

In [18]:
s = 'Hello, world'

In [19]:
type(s)

str

In [20]:
s[0:4]

'Hell'

In [21]:
s + '!'

'Hello, world!'

In [22]:
s

'Hello, world'

In [23]:
s = s + '!'

In [24]:
s

'Hello, world!'

Lists are _mutable_ sequences of anything.

In [25]:
l = [0, 1, 1, 2, 3, 5, 8]

In [26]:
m = [5, 2, 'a', 'xxx', True, [0, 1]]

In [27]:
l[0:3]

[0, 1, 1]

In [28]:
m[4]

True

In [29]:
m[4] = False

In [30]:
m[4:]

[False, [0, 1]]

Tuples are immutable sequences of anything (similar to lists except you can't change them).

In [31]:
n = (3, 5, 6)

In [32]:
n[0]

3

In [33]:
n[0] = 2

TypeError: 'tuple' object does not support item assignment

#### Sets

Sets are unordered collections of unique objects.

In [34]:
s1 = {'a', 'b', 'c'}
s2 = {'a', 'd', 'e'}

In [35]:
s1 & s2

{'a'}

In [36]:
s1 | s2

{'a', 'b', 'c', 'd', 'e'}

In [37]:
s3 = set(l)
s4 = set(m[0:2])

In [38]:
s3 & s4

{2, 5}

In [39]:
s3 | s4

{0, 1, 2, 3, 5, 8}

In [40]:
s3 - s4

{0, 1, 3, 8}

#### Dictionaries

Dictionaries or 'dicts' are hash tables, where a key points to a value.

In [41]:
d = {'name': 'John Doe', 'age': 27, 'dob': '7/20/1989'}

In [42]:
d['name']

'John Doe'

In [43]:
d['zip'] = 92039

In [44]:
d

{'age': 27, 'dob': '7/20/1989', 'name': 'John Doe', 'zip': 92039}

### Loops and control structures

#### Boolean and comparison operations

In [45]:
x = 5
(x < 6) and (x > 4)

True

In [46]:
x != 4

True

In [47]:
5 in [3, 4, 5]

True

In [48]:
'ell' in 'Hello'

True

In [49]:
len('Hello') >= 5

True

#### if tests

In [50]:
if 'd' in 'abc':
    print('Learn your alphabet.')
elif (2 + 2 == 5):
    print('Sometimes yes.')
else: 
    print('Nothing is true.')    

Nothing is true.


#### while loops

In [51]:
i = 0
while (i < 5):
    print(i)
    i += 1

0
1
2
3
4


In [52]:
i

5

#### for loops

In [53]:
for x in [0, 1, 2, 3, 4]:
    print(x**2)

0
1
4
9
16


### numpy, scipy, math

NumPy is the core numerical computing package in Python. SciPy contains additional routines for scientific work. Math provides additional useful functions.

In [54]:
mylist = [0, 2, 4]
np.array(mylist)

array([0, 2, 4])

In [55]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [56]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [57]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [58]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [59]:
np.linspace(0, 10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [60]:
np.linspace(0, 10, 11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [61]:
np.random.rand()

0.657836927907001

In [62]:
np.random.rand(5)

array([  3.08887005e-04,   6.16476936e-03,   6.21246561e-01,
         3.35012098e-02,   1.19380232e-01])

In [63]:
math.floor(4.22)

4

In [64]:
math.ceil(4.22)

5

In [65]:
math.factorial(5)

120

In [66]:
stats.stats.linalg?

In [67]:
np.arange?